// Timed lyrics transcript for "Young and Beautiful" by Lana Del Rey
export const LYRICS_DATA = [
  { time: 15, text: "♪ I've seen the world, done it all, had my cake now ♪" },
  { time: 24, text: "♪ Diamonds, brilliant and Bel Air, now ♪" },
  { time: 31, text: "♪ Hot summer nights, mid July, when you and I were forever wild ♪" },
  { time: 40, text: "♪ The crazy days, city lights, the way you play with me like a child ♪" },
  { time: 50, text: "♪ Will you still love me when I'm no longer young and beautiful ♪" },
  { time: 58, text: "♪ Will you still love me when I got nothing but my aching soul ♪" },
  { time: 65, text: "♪ I know you will, I know you will, I know that you will ♪" },
  { time: 73, text: "♪ Will you still love me when I'm no longer beautiful ♪" },
  { time: 81, text: "♪ I've seen the world, lit it up as my stage now ♪" },
  { time: 90, text: "♪ Channeling angels in the new age now ♪" },
  { time: 98, text: "♪ Hot summer days, rock and roll, the way you play for me at your show ♪" },
  { time: 106, text: "♪ And all the ways I got to know your pretty face and electric soul ♪" },
  { time: 116, text: "♪ Will you still love me when I'm no longer young and beautiful ♪" },
  { time: 124, text: "♪ Will you still love me when I got nothing but my aching soul ♪" },
  { time: 131, text: "♪ I know you will, I know you will, I know that you will ♪" },
  { time: 139, text: "♪ Will you still love me when I'm no longer beautiful ♪" },
  { time: 148, text: "♪ Dear Lord when I get to heaven, please let me bring my man ♪" },
  { time: 157, text: "♪ When he comes tell me that you'll let him in, Father tell me if you can ♪" },
  { time: 164, text: "♪ All that grace, all that body, all that face, makes me wanna party ♪" },
  { time: 173, text: "♪ He's my sun, he makes me shine like diamonds ♪" },
  { time: 182, text: "♪ Will you still love me when I'm no longer young and beautiful ♪" },
  { time: 190, text: "♪ Will you still love me when I got nothing but my aching soul ♪" },
  { time: 197, text: "♪ I know you will, I know you will, I know that you will ♪" },
  { time: 205, text: "♪ Will you still love me when I'm no longer beautiful ♪" },
  { time: 214, text: "♪ Will you still love me when I'm no longer beautiful ♪" },
  { time: 222, text: "♪ Will you still love me when I'm not young and beautiful ♪" }
];
